apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "chart.fullname" . }}-app-key-manager-role"
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "update", "list" ]
