apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "chart.fullname" . }}-app-key-manager-rolebinding"
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "chart.fullname" . }}-app-key"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ include "chart.fullname" . }}-app-key-manager-role"
  apiGroup: rbac.authorization.k8s.io
