apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-generate-app-key
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      serviceAccountName: "{{ include "chart.fullname" . }}-app-key"
      containers:
        - name: generate-app-key
          image: bitnami/kubectl:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              if ! kubectl get secret {{ .Values.appKeySecret.name }}; then
                APP_KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c32)
                echo "Creating app key secret: $APP_KEY"
                kubectl create secret generic {{ .Values.appKeySecret.name }} --from-literal=app_key=$APP_KEY
              else
                echo "App key secret already exists: {{ .Values.appKeySecret.name }}"
              fi
      restartPolicy: OnFailure
